import { shuffleArray } from './gameUtils';
import type { Question } from "@/types/game";

interface CountryFlag {
  name: string;
  code: string;
  flagUrl: string;
  aliases?: string[];
}

// World flags data
export const worldFlagsList: CountryFlag[] = [
  { code: 'af', name: 'Afghanistan', flagUrl: 'https://flagcdn.com/w640/af.png' },
  { code: 'ax', name: 'Åland Islands', flagUrl: 'https://flagcdn.com/w640/ax.png' },
  { code: 'al', name: 'Albania', flagUrl: 'https://flagcdn.com/w640/al.png' },
  { code: 'dz', name: 'Algeria', flagUrl: 'https://flagcdn.com/w640/dz.png' },
  { code: 'as', name: 'American Samoa', flagUrl: 'https://flagcdn.com/w640/as.png' },
  { code: 'ad', name: 'Andorra', flagUrl: 'https://flagcdn.com/w640/ad.png' },
  { code: 'ao', name: 'Angola', flagUrl: 'https://flagcdn.com/w640/ao.png' },
  { code: 'ai', name: 'Anguilla', flagUrl: 'https://flagcdn.com/w640/ai.png' },
  { code: 'aq', name: 'Antarctica', flagUrl: 'https://flagcdn.com/w640/aq.png' },
  { code: 'ag', name: 'Antigua and Barbuda', flagUrl: 'https://flagcdn.com/w640/ag.png' },
  { code: 'ar', name: 'Argentina', flagUrl: 'https://flagcdn.com/w640/ar.png' },
  { code: 'am', name: 'Armenia', flagUrl: 'https://flagcdn.com/w640/am.png' },
  { code: 'aw', name: 'Aruba', flagUrl: 'https://flagcdn.com/w640/aw.png' },
  { code: 'au', name: 'Australia', flagUrl: 'https://flagcdn.com/w640/au.png' },
  { code: 'at', name: 'Austria', flagUrl: 'https://flagcdn.com/w640/at.png' },
  { code: 'az', name: 'Azerbaijan', flagUrl: 'https://flagcdn.com/w640/az.png' },
  { code: 'bs', name: 'Bahamas', flagUrl: 'https://flagcdn.com/w640/bs.png' },
  { code: 'bh', name: 'Bahrain', flagUrl: 'https://flagcdn.com/w640/bh.png' },
  { code: 'bd', name: 'Bangladesh', flagUrl: 'https://flagcdn.com/w640/bd.png' },
  { code: 'bb', name: 'Barbados', flagUrl: 'https://flagcdn.com/w640/bb.png' },
  { code: 'by', name: 'Belarus', flagUrl: 'https://flagcdn.com/w640/by.png' },
  { code: 'be', name: 'Belgium', flagUrl: 'https://flagcdn.com/w640/be.png' },
  { code: 'bz', name: 'Belize', flagUrl: 'https://flagcdn.com/w640/bz.png' },
  { code: 'bj', name: 'Benin', flagUrl: 'https://flagcdn.com/w640/bj.png' },
  { code: 'bm', name: 'Bermuda', flagUrl: 'https://flagcdn.com/w640/bm.png' },
  { code: 'bt', name: 'Bhutan', flagUrl: 'https://flagcdn.com/w640/bt.png' },
  { code: 'bo', name: 'Bolivia', flagUrl: 'https://flagcdn.com/w640/bo.png', aliases: ['Plurinational State of Bolivia'] },
  { code: 'ba', name: 'Bosnia and Herzegovina', flagUrl: 'https://flagcdn.com/w640/ba.png' },
  { code: 'bw', name: 'Botswana', flagUrl: 'https://flagcdn.com/w640/bw.png' },
  { code: 'bv', name: 'Bouvet Island', flagUrl: 'https://flagcdn.com/w640/bv.png' },
  { code: 'br', name: 'Brazil', flagUrl: 'https://flagcdn.com/w640/br.png' },
  { code: 'io', name: 'British Indian Ocean Territory', flagUrl: 'https://flagcdn.com/w640/io.png' },
  { code: 'vg', name: 'British Virgin Islands', flagUrl: 'https://flagcdn.com/w640/vg.png', aliases: ['BVI'] },
  { code: 'bn', name: 'Brunei', flagUrl: 'https://flagcdn.com/w640/bn.png' },
  { code: 'bg', name: 'Bulgaria', flagUrl: 'https://flagcdn.com/w640/bg.png' },
  { code: 'bf', name: 'Burkina Faso', flagUrl: 'https://flagcdn.com/w640/bf.png' },
  { code: 'bi', name: 'Burundi', flagUrl: 'https://flagcdn.com/w640/bi.png' },
  { code: 'kh', name: 'Cambodia', flagUrl: 'https://flagcdn.com/w640/kh.png' },
  { code: 'cm', name: 'Cameroon', flagUrl: 'https://flagcdn.com/w640/cm.png' },
  { code: 'ca', name: 'Canada', flagUrl: 'https://flagcdn.com/w640/ca.png' },
  { code: 'cv', name: 'Cape Verde', flagUrl: 'https://flagcdn.com/w640/cv.png' },
  { code: 'bq', name: 'Caribbean Netherlands', flagUrl: 'https://flagcdn.com/w640/bq.png' },
  { code: 'ky', name: 'Cayman Islands', flagUrl: 'https://flagcdn.com/w640/ky.png' },
  { code: 'cf', name: 'Central African Republic', flagUrl: 'https://flagcdn.com/w640/cf.png' },
  { code: 'td', name: 'Chad', flagUrl: 'https://flagcdn.com/w640/td.png' },
  { code: 'cl', name: 'Chile', flagUrl: 'https://flagcdn.com/w640/cl.png' },
  { code: 'cn', name: 'China', flagUrl: 'https://flagcdn.com/w640/cn.png' },
  { code: 'cx', name: 'Christmas Island', flagUrl: 'https://flagcdn.com/w640/cx.png' },
  { code: 'cc', name: 'Cocos Islands', flagUrl: 'https://flagcdn.com/w640/cc.png' },
  { code: 'co', name: 'Colombia', flagUrl: 'https://flagcdn.com/w640/co.png' },
  { code: 'km', name: 'Comoros', flagUrl: 'https://flagcdn.com/w640/km.png' },
  { code: 'cg', name: 'Republic of the Congo', flagUrl: 'https://flagcdn.com/w640/cg.png', aliases: ['Congo-Brazzaville'] },
  { code: 'cd', name: 'DR Congo', flagUrl: 'https://flagcdn.com/w640/cd.png', aliases: ['Democratic Republic of the Congo'] },
  { code: 'ck', name: 'Cook Islands', flagUrl: 'https://flagcdn.com/w640/ck.png' },
  { code: 'cr', name: 'Costa Rica', flagUrl: 'https://flagcdn.com/w640/cr.png' },
  { code: 'ci', name: "Côte d'Ivoire", flagUrl: 'https://flagcdn.com/w640/ci.png', aliases: ['Ivory Coast'] },
  { code: 'hr', name: 'Croatia', flagUrl: 'https://flagcdn.com/w640/hr.png' },
  { code: 'cu', name: 'Cuba', flagUrl: 'https://flagcdn.com/w640/cu.png' },
  { code: 'cw', name: 'Curaçao', flagUrl: 'https://flagcdn.com/w640/cw.png' },
  { code: 'cy', name: 'Cyprus', flagUrl: 'https://flagcdn.com/w640/cy.png' },
  { code: 'cz', name: 'Czechia', flagUrl: 'https://flagcdn.com/w640/cz.png', aliases: ['Czech Republic'] },
  { code: 'dk', name: 'Denmark', flagUrl: 'https://flagcdn.com/w640/dk.png' },
  { code: 'dj', name: 'Djibouti', flagUrl: 'https://flagcdn.com/w640/dj.png' },
  { code: 'dm', name: 'Dominica', flagUrl: 'https://flagcdn.com/w640/dm.png' },
  { code: 'do', name: 'Dominican Republic', flagUrl: 'https://flagcdn.com/w640/do.png' },
  { code: 'ec', name: 'Ecuador', flagUrl: 'https://flagcdn.com/w640/ec.png' },
  { code: 'eg', name: 'Egypt', flagUrl: 'https://flagcdn.com/w640/eg.png' },
  { code: 'sv', name: 'El Salvador', flagUrl: 'https://flagcdn.com/w640/sv.png' },
  { code: 'gb-eng', name: 'England', flagUrl: 'https://flagcdn.com/w640/gb-eng.png' },
  { code: 'gq', name: 'Equatorial Guinea', flagUrl: 'https://flagcdn.com/w640/gq.png' },
  { code: 'er', name: 'Eritrea', flagUrl: 'https://flagcdn.com/w640/er.png' },
  { code: 'ee', name: 'Estonia', flagUrl: 'https://flagcdn.com/w640/ee.png' },
  { code: 'sz', name: 'Eswatini', flagUrl: 'https://flagcdn.com/w640/sz.png', aliases: ['Swaziland'] },
  { code: 'et', name: 'Ethiopia', flagUrl: 'https://flagcdn.com/w640/et.png' },
  { code: 'fk', name: 'Falkland Islands', flagUrl: 'https://flagcdn.com/w640/fk.png' },
  { code: 'fo', name: 'Faroe Islands', flagUrl: 'https://flagcdn.com/w640/fo.png' },
  { code: 'fj', name: 'Fiji', flagUrl: 'https://flagcdn.com/w640/fj.png' },
  { code: 'fi', name: 'Finland', flagUrl: 'https://flagcdn.com/w640/fi.png' },
  { code: 'fr', name: 'France', flagUrl: 'https://flagcdn.com/w640/fr.png' },
  { code: 'gf', name: 'French Guiana', flagUrl: 'https://flagcdn.com/w640/gf.png' },
  { code: 'pf', name: 'French Polynesia', flagUrl: 'https://flagcdn.com/w640/pf.png' },
  { code: 'tf', name: 'French Southern Territories', flagUrl: 'https://flagcdn.com/w640/tf.png' },
  { code: 'ga', name: 'Gabon', flagUrl: 'https://flagcdn.com/w640/ga.png' },
  { code: 'gm', name: 'Gambia', flagUrl: 'https://flagcdn.com/w640/gm.png' },
  { code: 'ge', name: 'Georgia', flagUrl: 'https://flagcdn.com/w640/ge.png' },
  { code: 'de', name: 'Germany', flagUrl: 'https://flagcdn.com/w640/de.png' },
  { code: 'gh', name: 'Ghana', flagUrl: 'https://flagcdn.com/w640/gh.png' },
  { code: 'gi', name: 'Gibraltar', flagUrl: 'https://flagcdn.com/w640/gi.png' },
  { code: 'gr', name: 'Greece', flagUrl: 'https://flagcdn.com/w640/gr.png' },
  { code: 'gl', name: 'Greenland', flagUrl: 'https://flagcdn.com/w640/gl.png' },
  { code: 'gd', name: 'Grenada', flagUrl: 'https://flagcdn.com/w640/gd.png' },
  { code: 'gp', name: 'Guadeloupe', flagUrl: 'https://flagcdn.com/w640/gp.png' },
  { code: 'gu', name: 'Guam', flagUrl: 'https://flagcdn.com/w640/gu.png' },
  { code: 'gt', name: 'Guatemala', flagUrl: 'https://flagcdn.com/w640/gt.png' },
  { code: 'gg', name: 'Guernsey', flagUrl: 'https://flagcdn.com/w640/gg.png' },
  { code: 'gn', name: 'Guinea', flagUrl: 'https://flagcdn.com/w640/gn.png' },
  { code: 'gw', name: 'Guinea-Bissau', flagUrl: 'https://flagcdn.com/w640/gw.png' },
  { code: 'gy', name: 'Guyana', flagUrl: 'https://flagcdn.com/w640/gy.png' },
  { code: 'ht', name: 'Haiti', flagUrl: 'https://flagcdn.com/w640/ht.png' },
  { code: 'hm', name: 'Heard Island and McDonald Islands', flagUrl: 'https://flagcdn.com/w640/hm.png' },
  { code: 'hn', name: 'Honduras', flagUrl: 'https://flagcdn.com/w640/hn.png' },
  { code: 'hk', name: 'Hong Kong', flagUrl: 'https://flagcdn.com/w640/hk.png' },
  { code: 'hu', name: 'Hungary', flagUrl: 'https://flagcdn.com/w640/hu.png' },
  { code: 'is', name: 'Iceland', flagUrl: 'https://flagcdn.com/w640/is.png' },
  { code: 'in', name: 'India', flagUrl: 'https://flagcdn.com/w640/in.png' },
  { code: 'id', name: 'Indonesia', flagUrl: 'https://flagcdn.com/w640/id.png' },
  { code: 'ir', name: 'Iran', flagUrl: 'https://flagcdn.com/w640/ir.png', aliases: ['Islamic Republic of Iran'] },
  { code: 'iq', name: 'Iraq', flagUrl: 'https://flagcdn.com/w640/iq.png' },
  { code: 'ie', name: 'Ireland', flagUrl: 'https://flagcdn.com/w640/ie.png' },
  { code: 'im', name: 'Isle of Man', flagUrl: 'https://flagcdn.com/w640/im.png' },
  { code: 'il', name: 'Israel', flagUrl: 'https://flagcdn.com/w640/il.png' },
  { code: 'it', name: 'Italy', flagUrl: 'https://flagcdn.com/w640/it.png' },
  { code: 'jm', name: 'Jamaica', flagUrl: 'https://flagcdn.com/w640/jm.png' },
  { code: 'jp', name: 'Japan', flagUrl: 'https://flagcdn.com/w640/jp.png' },
  { code: 'je', name: 'Jersey', flagUrl: 'https://flagcdn.com/w640/je.png' },
  { code: 'jo', name: 'Jordan', flagUrl: 'https://flagcdn.com/w640/jo.png' },
  { code: 'kz', name: 'Kazakhstan', flagUrl: 'https://flagcdn.com/w640/kz.png' },
  { code: 'ke', name: 'Kenya', flagUrl: 'https://flagcdn.com/w640/ke.png' },
  { code: 'ki', name: 'Kiribati', flagUrl: 'https://flagcdn.com/w640/ki.png' },
  { code: 'kp', name: 'North Korea', flagUrl: 'https://flagcdn.com/w640/kp.png', aliases: ['DPR Korea'] },
  { code: 'kr', name: 'South Korea', flagUrl: 'https://flagcdn.com/w640/kr.png', aliases: ['Republic of Korea', 'Korea, Republic of'] },
  { code: 'xk', name: 'Kosovo', flagUrl: 'https://flagcdn.com/w640/xk.png' },
  { code: 'kw', name: 'Kuwait', flagUrl: 'https://flagcdn.com/w640/kw.png' },
  { code: 'kg', name: 'Kyrgyzstan', flagUrl: 'https://flagcdn.com/w640/kg.png' },
  { code: 'la', name: 'Laos', flagUrl: 'https://flagcdn.com/w640/la.png' },
  { code: 'lv', name: 'Latvia', flagUrl: 'https://flagcdn.com/w640/lv.png' },
  { code: 'lb', name: 'Lebanon', flagUrl: 'https://flagcdn.com/w640/lb.png' },
  { code: 'ls', name: 'Lesotho', flagUrl: 'https://flagcdn.com/w640/ls.png' },
  { code: 'lr', name: 'Liberia', flagUrl: 'https://flagcdn.com/w640/lr.png' },
  { code: 'ly', name: 'Libya', flagUrl: 'https://flagcdn.com/w640/ly.png' },
  { code: 'li', name: 'Liechtenstein', flagUrl: 'https://flagcdn.com/w640/li.png' },
  { code: 'lt', name: 'Lithuania', flagUrl: 'https://flagcdn.com/w640/lt.png' },
  { code: 'lu', name: 'Luxembourg', flagUrl: 'https://flagcdn.com/w640/lu.png' },
  { code: 'mo', name: 'Macau', flagUrl: 'https://flagcdn.com/w640/mo.png', aliases: ['Macao'] },
  { code: 'mg', name: 'Madagascar', flagUrl: 'https://flagcdn.com/w640/mg.png' },
  { code: 'mw', name: 'Malawi', flagUrl: 'https://flagcdn.com/w640/mw.png' },
  { code: 'my', name: 'Malaysia', flagUrl: 'https://flagcdn.com/w640/my.png' },
  { code: 'mv', name: 'Maldives', flagUrl: 'https://flagcdn.com/w640/mv.png' },
  { code: 'ml', name: 'Mali', flagUrl: 'https://flagcdn.com/w640/ml.png' },
  { code: 'mt', name: 'Malta', flagUrl: 'https://flagcdn.com/w640/mt.png' },
  { code: 'mh', name: 'Marshall Islands', flagUrl: 'https://flagcdn.com/w640/mh.png' },
  { code: 'mq', name: 'Martinique', flagUrl: 'https://flagcdn.com/w640/mq.png' },
  { code: 'mr', name: 'Mauritania', flagUrl: 'https://flagcdn.com/w640/mr.png' },
  { code: 'mu', name: 'Mauritius', flagUrl: 'https://flagcdn.com/w640/mu.png' },
  { code: 'yt', name: 'Mayotte', flagUrl: 'https://flagcdn.com/w640/yt.png' },
  { code: 'mx', name: 'Mexico', flagUrl: 'https://flagcdn.com/w640/mx.png' },
  { code: 'fm', name: 'Micronesia', flagUrl: 'https://flagcdn.com/w640/fm.png', aliases: ['Federated States of Micronesia', 'FSM'] },
  { code: 'md', name: 'Moldova', flagUrl: 'https://flagcdn.com/w640/md.png', aliases: ['Republic of Moldova'] },
  { code: 'mc', name: 'Monaco', flagUrl: 'https://flagcdn.com/w640/mc.png' },
  { code: 'mn', name: 'Mongolia', flagUrl: 'https://flagcdn.com/w640/mn.png' },
  { code: 'me', name: 'Montenegro', flagUrl: 'https://flagcdn.com/w640/me.png' },
  { code: 'ms', name: 'Montserrat', flagUrl: 'https://flagcdn.com/w640/ms.png' },
  { code: 'ma', name: 'Morocco', flagUrl: 'https://flagcdn.com/w640/ma.png' },
  { code: 'mz', name: 'Mozambique', flagUrl: 'https://flagcdn.com/w640/mz.png' },
  { code: 'mm', name: 'Myanmar', flagUrl: 'https://flagcdn.com/w640/mm.png', aliases: ['Burma'] },
  { code: 'na', name: 'Namibia', flagUrl: 'https://flagcdn.com/w640/na.png' },
  { code: 'nr', name: 'Nauru', flagUrl: 'https://flagcdn.com/w640/nr.png' },
  { code: 'np', name: 'Nepal', flagUrl: 'https://flagcdn.com/w640/np.png' },
  { code: 'nl', name: 'Netherlands', flagUrl: 'https://flagcdn.com/w640/nl.png' },
  { code: 'nc', name: 'New Caledonia', flagUrl: 'https://flagcdn.com/w640/nc.png' },
  { code: 'nz', name: 'New Zealand', flagUrl: 'https://flagcdn.com/w640/nz.png' },
  { code: 'ni', name: 'Nicaragua', flagUrl: 'https://flagcdn.com/w640/ni.png' },
  { code: 'ne', name: 'Niger', flagUrl: 'https://flagcdn.com/w640/ne.png' },
  { code: 'ng', name: 'Nigeria', flagUrl: 'https://flagcdn.com/w640/ng.png' },
  { code: 'nu', name: 'Niue', flagUrl: 'https://flagcdn.com/w640/nu.png' },
  { code: 'nf', name: 'Norfolk Island', flagUrl: 'https://flagcdn.com/w640/nf.png' },
  { code: 'mk', name: 'North Macedonia', flagUrl: 'https://flagcdn.com/w640/mk.png' },
  { code: 'gb-nir', name: 'Northern Ireland', flagUrl: 'https://flagcdn.com/w640/gb-nir.png' },
  { code: 'mp', name: 'Northern Mariana Islands', flagUrl: 'https://flagcdn.com/w640/mp.png' },
  { code: 'no', name: 'Norway', flagUrl: 'https://flagcdn.com/w640/no.png' },
  { code: 'om', name: 'Oman', flagUrl: 'https://flagcdn.com/w640/om.png' },
  { code: 'pk', name: 'Pakistan', flagUrl: 'https://flagcdn.com/w640/pk.png' },
  { code: 'pw', name: 'Palau', flagUrl: 'https://flagcdn.com/w640/pw.png' },
  { code: 'ps', name: 'Palestine', flagUrl: 'https://flagcdn.com/w640/ps.png' },
  { code: 'pa', name: 'Panama', flagUrl: 'https://flagcdn.com/w640/pa.png' },
  { code: 'pg', name: 'Papua New Guinea', flagUrl: 'https://flagcdn.com/w640/pg.png' },
  { code: 'py', name: 'Paraguay', flagUrl: 'https://flagcdn.com/w640/py.png' },
  { code: 'pe', name: 'Peru', flagUrl: 'https://flagcdn.com/w640/pe.png' },
  { code: 'ph', name: 'Philippines', flagUrl: 'https://flagcdn.com/w640/ph.png' },
  { code: 'pn', name: 'Pitcairn Islands', flagUrl: 'https://flagcdn.com/w640/pn.png' },
  { code: 'pl', name: 'Poland', flagUrl: 'https://flagcdn.com/w640/pl.png' },
  { code: 'pt', name: 'Portugal', flagUrl: 'https://flagcdn.com/w640/pt.png' },
  { code: 'pr', name: 'Puerto Rico', flagUrl: 'https://flagcdn.com/w640/pr.png' },
  { code: 'qa', name: 'Qatar', flagUrl: 'https://flagcdn.com/w640/qa.png' },
  { code: 're', name: 'Réunion', flagUrl: 'https://flagcdn.com/w640/re.png', aliases: ['Reunion'] },
  { code: 'ro', name: 'Romania', flagUrl: 'https://flagcdn.com/w640/ro.png' },
  { code: 'ru', name: 'Russia', flagUrl: 'https://flagcdn.com/w640/ru.png', aliases: ['Russian Federation'] },
  { code: 'rw', name: 'Rwanda', flagUrl: 'https://flagcdn.com/w640/rw.png' },
  { code: 'bl', name: 'Saint Barthélemy', flagUrl: 'https://flagcdn.com/w640/bl.png' },
  { code: 'sh', name: 'Saint Helena, Ascension and Tristan da Cunha', flagUrl: 'https://flagcdn.com/w640/sh.png' },
  { code: 'kn', name: 'Saint Kitts and Nevis', flagUrl: 'https://flagcdn.com/w640/kn.png' },
  { code: 'lc', name: 'Saint Lucia', flagUrl: 'https://flagcdn.com/w640/lc.png' },
  { code: 'mf', name: 'Saint Martin', flagUrl: 'https://flagcdn.com/w640/mf.png' },
  { code: 'pm', name: 'Saint Pierre and Miquelon', flagUrl: 'https://flagcdn.com/w640/pm.png' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', flagUrl: 'https://flagcdn.com/w640/vc.png' },
  { code: 'ws', name: 'Samoa', flagUrl: 'https://flagcdn.com/w640/ws.png' },
  { code: 'sm', name: 'San Marino', flagUrl: 'https://flagcdn.com/w640/sm.png' },
  { code: 'st', name: 'São Tomé and Príncipe', flagUrl: 'https://flagcdn.com/w640/st.png' },
  { code: 'sa', name: 'Saudi Arabia', flagUrl: 'https://flagcdn.com/w640/sa.png' },
  { code: 'gb-sct', name: 'Scotland', flagUrl: 'https://flagcdn.com/w640/gb-sct.png' },
  { code: 'sn', name: 'Senegal', flagUrl: 'https://flagcdn.com/w640/sn.png' },
  { code: 'rs', name: 'Serbia', flagUrl: 'https://flagcdn.com/w640/rs.png' },
  { code: 'sc', name: 'Seychelles', flagUrl: 'https://flagcdn.com/w640/sc.png' },
  { code: 'sl', name: 'Sierra Leone', flagUrl: 'https://flagcdn.com/w640/sl.png' },
  { code: 'sg', name: 'Singapore', flagUrl: 'https://flagcdn.com/w640/sg.png' },
  { code: 'sx', name: 'Sint Maarten', flagUrl: 'https://flagcdn.com/w640/sx.png' },
  { code: 'sk', name: 'Slovakia', flagUrl: 'https://flagcdn.com/w640/sk.png' },
  { code: 'si', name: 'Slovenia', flagUrl: 'https://flagcdn.com/w640/si.png' },
  { code: 'sb', name: 'Solomon Islands', flagUrl: 'https://flagcdn.com/w640/sb.png' },
  { code: 'so', name: 'Somalia', flagUrl: 'https://flagcdn.com/w640/so.png' },
  { code: 'za', name: 'South Africa', flagUrl: 'https://flagcdn.com/w640/za.png' },
  { code: 'gs', name: 'South Georgia', flagUrl: 'https://flagcdn.com/w640/gs.png' },
  { code: 'ss', name: 'South Sudan', flagUrl: 'https://flagcdn.com/w640/ss.png' },
  { code: 'es', name: 'Spain', flagUrl: 'https://flagcdn.com/w640/es.png' },
  { code: 'lk', name: 'Sri Lanka', flagUrl: 'https://flagcdn.com/w640/lk.png' },
  { code: 'sd', name: 'Sudan', flagUrl: 'https://flagcdn.com/w640/sd.png' },
  { code: 'sr', name: 'Suriname', flagUrl: 'https://flagcdn.com/w640/sr.png' },
  { code: 'sj', name: 'Svalbard and Jan Mayen', flagUrl: 'https://flagcdn.com/w640/sj.png' },
  { code: 'se', name: 'Sweden', flagUrl: 'https://flagcdn.com/w640/se.png' },
  { code: 'ch', name: 'Switzerland', flagUrl: 'https://flagcdn.com/w640/ch.png' },
  { code: 'sy', name: 'Syria', flagUrl: 'https://flagcdn.com/w640/sy.png', aliases: ['Syrian Arab Republic'] },
  { code: 'tw', name: 'Taiwan', flagUrl: 'https://flagcdn.com/w640/tw.png' },
  { code: 'tj', name: 'Tajikistan', flagUrl: 'https://flagcdn.com/w640/tj.png' },
  { code: 'tz', name: 'Tanzania', flagUrl: 'https://flagcdn.com/w640/tz.png', aliases: ['United Republic of Tanzania'] },
  { code: 'th', name: 'Thailand', flagUrl: 'https://flagcdn.com/w640/th.png' },
  { code: 'tl', name: 'Timor-Leste', flagUrl: 'https://flagcdn.com/w640/tl.png' },
  { code: 'tg', name: 'Togo', flagUrl: 'https://flagcdn.com/w640/tg.png' },
  { code: 'tk', name: 'Tokelau', flagUrl: 'https://flagcdn.com/w640/tk.png' },
  { code: 'to', name: 'Tonga', flagUrl: 'https://flagcdn.com/w640/to.png' },
  { code: 'tt', name: 'Trinidad and Tobago', flagUrl: 'https://flagcdn.com/w640/tt.png' },
  { code: 'tn', name: 'Tunisia', flagUrl: 'https://flagcdn.com/w640/tn.png' },
  { code: 'tr', name: 'Turkey', flagUrl: 'https://flagcdn.com/w640/tr.png' },
  { code: 'tm', name: 'Turkmenistan', flagUrl: 'https://flagcdn.com/w640/tm.png' },
  { code: 'tc', name: 'Turks and Caicos Islands', flagUrl: 'https://flagcdn.com/w640/tc.png' },
  { code: 'tv', name: 'Tuvalu', flagUrl: 'https://flagcdn.com/w640/tv.png' },
  { code: 'ug', name: 'Uganda', flagUrl: 'https://flagcdn.com/w640/ug.png' },
  { code: 'ua', name: 'Ukraine', flagUrl: 'https://flagcdn.com/w640/ua.png' },
  { code: 'ae', name: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/w640/ae.png', aliases: ['UAE'] },
  { code: 'gb', name: 'United Kingdom', flagUrl: 'https://flagcdn.com/w640/gb.png', aliases: ['UK', 'Britain', 'Great Britain'] },
  { code: 'us', name: 'United States', flagUrl: 'https://flagcdn.com/w640/us.png', aliases: ['USA', 'America', 'United States of America'] },
  { code: 'um', name: 'United States Minor Outlying Islands', flagUrl: 'https://flagcdn.com/w640/um.png' },
  { code: 'vi', name: 'United States Virgin Islands', flagUrl: 'https://flagcdn.com/w640/vi.png', aliases: ['USVI'] },
  { code: 'uy', name: 'Uruguay', flagUrl: 'https://flagcdn.com/w640/uy.png' },
  { code: 'uz', name: 'Uzbekistan', flagUrl: 'https://flagcdn.com/w640/uz.png' },
  { code: 'vu', name: 'Vanuatu', flagUrl: 'https://flagcdn.com/w640/vu.png' },
  { code: 'va', name: 'Vatican City', flagUrl: 'https://flagcdn.com/w640/va.png', aliases: ['Holy See'] },
  { code: 've', name: 'Venezuela', flagUrl: 'https://flagcdn.com/w640/ve.png', aliases: ['Bolivarian Republic of Venezuela'] },
  { code: 'vn', name: 'Vietnam', flagUrl: 'https://flagcdn.com/w640/vn.png' },
  { code: 'gb-wls', name: 'Wales', flagUrl: 'https://flagcdn.com/w640/gb-wls.png' },
  { code: 'wf', name: 'Wallis and Futuna', flagUrl: 'https://flagcdn.com/w640/wf.png' },
  { code: 'eh', name: 'Western Sahara', flagUrl: 'https://flagcdn.com/w640/eh.png' },
  { code: 'ye', name: 'Yemen', flagUrl: 'https://flagcdn.com/w640/ye.png' },
  { code: 'zm', name: 'Zambia', flagUrl: 'https://flagcdn.com/w640/zm.png' },
  { code: 'zw', name: 'Zimbabwe', flagUrl: 'https://flagcdn.com/w640/zw.png' }
];

// US states data
export const usStatesList: CountryFlag[] = [
  { code: 'us-al', name: 'Alabama', flagUrl: 'https://flagcdn.com/w640/us-al.png', aliases: ['AL'] },
  { code: 'us-ak', name: 'Alaska', flagUrl: 'https://flagcdn.com/w640/us-ak.png', aliases: ['AK'] },
  { code: 'us-az', name: 'Arizona', flagUrl: 'https://flagcdn.com/w640/us-az.png', aliases: ['AZ'] },
  { code: 'us-ar', name: 'Arkansas', flagUrl: 'https://flagcdn.com/w640/us-ar.png', aliases: ['AR'] },
  { code: 'us-ca', name: 'California', flagUrl: 'https://flagcdn.com/w640/us-ca.png', aliases: ['CA'] },
  { code: 'us-co', name: 'Colorado', flagUrl: 'https://flagcdn.com/w640/us-co.png', aliases: ['CO'] },
  { code: 'us-ct', name: 'Connecticut', flagUrl: 'https://flagcdn.com/w640/us-ct.png', aliases: ['CT'] },
  { code: 'us-de', name: 'Delaware', flagUrl: 'https://flagcdn.com/w640/us-de.png', aliases: ['DE'] },
  { code: 'us-fl', name: 'Florida', flagUrl: 'https://flagcdn.com/w640/us-fl.png', aliases: ['FL'] },
  { code: 'us-ga', name: 'Georgia', flagUrl: 'https://flagcdn.com/w640/us-ga.png', aliases: ['GA'] },
  { code: 'us-hi', name: 'Hawaii', flagUrl: 'https://flagcdn.com/w640/us-hi.png', aliases: ['HI'] },
  { code: 'us-id', name: 'Idaho', flagUrl: 'https://flagcdn.com/w640/us-id.png', aliases: ['ID'] },
  { code: 'us-il', name: 'Illinois', flagUrl: 'https://flagcdn.com/w640/us-il.png', aliases: ['IL'] },
  { code: 'us-in', name: 'Indiana', flagUrl: 'https://flagcdn.com/w640/us-in.png', aliases: ['IN'] },
  { code: 'us-ia', name: 'Iowa', flagUrl: 'https://flagcdn.com/w640/us-ia.png', aliases: ['IA'] },
  { code: 'us-ks', name: 'Kansas', flagUrl: 'https://flagcdn.com/w640/us-ks.png', aliases: ['KS'] },
  { code: 'us-ky', name: 'Kentucky', flagUrl: 'https://flagcdn.com/w640/us-ky.png', aliases: ['KY'] },
  { code: 'us-la', name: 'Louisiana', flagUrl: 'https://flagcdn.com/w640/us-la.png', aliases: ['LA'] },
  { code: 'us-me', name: 'Maine', flagUrl: 'https://flagcdn.com/w640/us-me.png', aliases: ['ME'] },
  { code: 'us-md', name: 'Maryland', flagUrl: 'https://flagcdn.com/w640/us-md.png', aliases: ['MD'] },
  { code: 'us-ma', name: 'Massachusetts', flagUrl: 'https://flagcdn.com/w640/us-ma.png', aliases: ['MA'] },
  { code: 'us-mi', name: 'Michigan', flagUrl: 'https://flagcdn.com/w640/us-mi.png', aliases: ['MI'] },
  { code: 'us-mn', name: 'Minnesota', flagUrl: 'https://flagcdn.com/w640/us-mn.png', aliases: ['MN'] },
  { code: 'us-ms', name: 'Mississippi', flagUrl: 'https://flagcdn.com/w640/us-ms.png', aliases: ['MS'] },
  { code: 'us-mo', name: 'Missouri', flagUrl: 'https://flagcdn.com/w640/us-mo.png', aliases: ['MO'] },
  { code: 'us-mt', name: 'Montana', flagUrl: 'https://flagcdn.com/w640/us-mt.png', aliases: ['MT'] },
  { code: 'us-ne', name: 'Nebraska', flagUrl: 'https://flagcdn.com/w640/us-ne.png', aliases: ['NE'] },
  { code: 'us-nv', name: 'Nevada', flagUrl: 'https://flagcdn.com/w640/us-nv.png', aliases: ['NV'] },
  { code: 'us-nh', name: 'New Hampshire', flagUrl: 'https://flagcdn.com/w640/us-nh.png', aliases: ['NH'] },
  { code: 'us-nj', name: 'New Jersey', flagUrl: 'https://flagcdn.com/w640/us-nj.png', aliases: ['NJ'] },
  { code: 'us-nm', name: 'New Mexico', flagUrl: 'https://flagcdn.com/w640/us-nm.png', aliases: ['NM'] },
  { code: 'us-ny', name: 'New York', flagUrl: 'https://flagcdn.com/w640/us-ny.png', aliases: ['NY'] },
  { code: 'us-nc', name: 'North Carolina', flagUrl: 'https://flagcdn.com/w640/us-nc.png', aliases: ['NC'] },
  { code: 'us-nd', name: 'North Dakota', flagUrl: 'https://flagcdn.com/w640/us-nd.png', aliases: ['ND'] },
  { code: 'us-oh', name: 'Ohio', flagUrl: 'https://flagcdn.com/w640/us-oh.png', aliases: ['OH'] },
  { code: 'us-ok', name: 'Oklahoma', flagUrl: 'https://flagcdn.com/w640/us-ok.png', aliases: ['OK'] },
  { code: 'us-or', name: 'Oregon', flagUrl: 'https://flagcdn.com/w640/us-or.png', aliases: ['OR'] },
  { code: 'us-pa', name: 'Pennsylvania', flagUrl: 'https://flagcdn.com/w640/us-pa.png', aliases: ['PA'] },
  { code: 'us-ri', name: 'Rhode Island', flagUrl: 'https://flagcdn.com/w640/us-ri.png', aliases: ['RI'] },
  { code: 'us-sc', name: 'South Carolina', flagUrl: 'https://flagcdn.com/w640/us-sc.png', aliases: ['SC'] },
  { code: 'us-sd', name: 'South Dakota', flagUrl: 'https://flagcdn.com/w640/us-sd.png', aliases: ['SD'] },
  { code: 'us-tn', name: 'Tennessee', flagUrl: 'https://flagcdn.com/w640/us-tn.png', aliases: ['TN'] },
  { code: 'us-tx', name: 'Texas', flagUrl: 'https://flagcdn.com/w640/us-tx.png', aliases: ['TX'] },
  { code: 'us-ut', name: 'Utah', flagUrl: 'https://flagcdn.com/w640/us-ut.png', aliases: ['UT'] },
  { code: 'us-vt', name: 'Vermont', flagUrl: 'https://flagcdn.com/w640/us-vt.png', aliases: ['VT'] },
  { code: 'us-va', name: 'Virginia', flagUrl: 'https://flagcdn.com/w640/us-va.png', aliases: ['VA'] },
  { code: 'us-wa', name: 'Washington', flagUrl: 'https://flagcdn.com/w640/us-wa.png', aliases: ['WA'] },
  { code: 'us-wv', name: 'West Virginia', flagUrl: 'https://flagcdn.com/w640/us-wv.png', aliases: ['WV'] },
  { code: 'us-wi', name: 'Wisconsin', flagUrl: 'https://flagcdn.com/w640/us-wi.png', aliases: ['WI'] },
  { code: 'us-wy', name: 'Wyoming', flagUrl: 'https://flagcdn.com/w640/us-wy.png', aliases: ['WY'] }
];

// Add helper function for string normalization
export function normalizeString(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s]/g, "")
    .trim();
}

// Update the generateQuestions function to include normalized versions
export function generateQuestions(mode: 'world' | 'us', count: number): Question[] {
  const sourceList = mode === 'world' ? worldFlagsList : usStatesList;
  const shuffledFlags = shuffleArray(sourceList);
  const selectedFlags = shuffledFlags.slice(0, count);

  const questions: Question[] = selectedFlags.map(flag => {
    // Get remaining flags (excluding current flag)
    const otherFlags = sourceList.filter(f => f.code !== flag.code);
    
    // Get 3 random wrong answers
    const wrongAnswers = shuffleArray(otherFlags)
      .slice(0, 3)
      .map(f => f.name);
    
    // Add correct answer at random position
    const options = [...wrongAnswers];
    const correctIndex = Math.floor(Math.random() * 4);
    options.splice(correctIndex, 0, flag.name);

    return {
      flagUrl: flag.flagUrl,
      correctAnswer: flag.name,
      aliases: [...(flag.aliases || []), normalizeString(flag.name)],
      options
    };
  });

  return questions;
}
